# Generated by Django 6.0 on 2026-02-21 12:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_firebaseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_type',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='frtg54', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
