# Generated by Django 6.0 on 2026-02-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_uploadedfile_file_size_uploadedfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('txt', 'Text'), ('doc', 'Document'), ('video', 'Video')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
