# Generated by Django 6.0 on 2026-02-24 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_uploadedfile_size_mb_alter_uploadedfile_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_size',
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('txt', 'Text'), ('docx', 'Document'), ('mp4', 'Video'), ('avi', 'Video'), ('mov', 'Video'), ('mkv', 'Video')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
