# Generated by Django 5.2.11 on 2026-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_video_videocheck_alter_firebaseuser_id_alter_otp_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocheck',
            name='confidence',
        ),
        migrations.RemoveField(
            model_name='videocheck',
            name='result_label',
        ),
        migrations.AddField(
            model_name='videocheck',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='is_fake',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
