# Generated by Django 5.2.11 on 2026-03-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_videocheck_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocheck',
            name='audio',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='black_frames',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='blur_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='brightness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='fps',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='motion_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='noise_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='quality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
