# Generated by Django 5.2.11 on 2026-03-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_videocheck_audio_videocheck_black_frames_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
