# Generated by Django 5.2.11 on 2026-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usersession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocheck',
            old_name='quality',
            new_name='quality_label',
        ),
        migrations.AddField(
            model_name='videocheck',
            name='problem_frames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='motion_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
