# Generated by Django 5.2.11 on 2026-03-12 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_videoresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.AddField(
            model_name='videocheck',
            name='faces_detected',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videocheck',
            name='inference_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='videoresult',
            name='faces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videoresult',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='videoresult',
            name='inference_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='videoresult',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
