# Generated by Django 5.2.11 on 2026-03-13 17:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_videoanalysis_videocheck_faces_detected_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.DeleteModel(
            name='VideoAnalysis',
        ),
        migrations.RenameField(
            model_name='videocheck',
            old_name='problem_frames',
            new_name='reference_text',
        ),
        migrations.RenameField(
            model_name='videocheck',
            old_name='quality_score',
            new_name='wer_score',
        ),
        migrations.RenameField(
            model_name='videoresult',
            old_name='created_at',
            new_name='analyzed_at',
        ),
        migrations.RenameField(
            model_name='videoresult',
            old_name='wer',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='firebaseuser',
            name='last_logout',
        ),
        migrations.RemoveField(
            model_name='videocheck',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='faces',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='faces_detected',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='inference_time',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='videoresult',
            name='user',
        ),
        migrations.AddField(
            model_name='videocheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocheck',
            name='decoding_method',
            field=models.CharField(default='wind', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoresult',
            name='result_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='email',
            field=models.EmailField(default='jathikakannan@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firebaseuser',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(default='unknown@example.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
    model_name='uploadedfile',
    name='size_mb',
    field=models.FloatField(default=0.0),
    preserve_default=False,
),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(default='unknown@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
    model_name='uploadedfile',
    name='user',
    field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
),
        migrations.AlterField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='audio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videoresult',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.videocheck'),
        ),
    ]
