# Generated by Django 5.2.11 on 2026-03-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_video_delete_videoanalysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocheck',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='videocheck',
            name='size_mb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='decoding_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='videocheck',
            name='inference_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
