# Generated by Django 5.2.11 on 2026-03-16 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_videocheck_uploaded_at_videocheck_size_mb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocheck',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
