# Generated by Django 5.2.11 on 2026-03-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_created_at_videocheck_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocheck',
            name='suggestion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
