# Generated by Django 5.2.11 on 2026-03-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_videocheck_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocheck',
            name='file',
            field=models.FileField(default='No suggestions', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
